"""
Start a project, and turn existing code into a task the tool can verify.

Two commands, both aimed at the same gap. Until now a fresh `pip install
qikly` produced a CLI that needed an `inputs_private/config/tasks/` directory
it had no way to create, and the use case the tool exists for, verifying code
somebody else wrote, required hand-writing a fifty line YAML whose
`interface:` block restates function signatures already present in the file
being pointed at.

`init` creates the directory layout and a commented starter task.

`scaffold` reads a Python file and writes the task for it: module path,
integration functions with their real signatures, and a system entrypoint
guess. It deliberately does NOT write `acceptance_criteria`. Those are the one
part that cannot be derived from the code, because criteria derived from an
implementation can only ever describe what that implementation already does,
and a bar that agrees with the code by construction is the exact failure this
whole tool exists to prevent.
"""
import ast
import os
import textwrap

TASK_TEMPLATE = '''# Generated by `qikly scaffold`. Two sections need you.
task_id: "{task_id}"

task_name: "{task_name}"

description: "{description}"

inputs:
{inputs}

outputs:
  - "outputs/data/{task_id}/output.json"

# Read out of {source_rel}. Check the entrypoint: it was guessed from the
# function names, and the guess is only as good as the naming.
interface:
  module: "{module}"
  integration_functions:
{functions}
  system_entrypoint: "{entrypoint}"

# TODO. What the code is supposed to do, in the words a person would use.
# The coding agent sees this section. Keep it at the level of a specification,
# not a checklist.
requirements:
  - "TODO: describe what this module must do"

# TODO. The checkable edge cases, written so each names a boundary value.
# The coding agent NEVER sees this section; test generation sees it in full,
# and that asymmetry is the whole point. Deriving these from the code would
# defeat it, so they are left for you.
#
# Write "rejects 0 and accepts 1" rather than "must be positive": the first
# forces a test at the boundary, the second invites a test at 5.
acceptance_criteria:
  - "TODO: one checkable statement, with its boundary value"
{seed_block}'''


# A scaffold produces two task files, because one command cannot know which of
# two different jobs you meant. Neither is a mode of the other and neither is
# commented out: you delete the one you are not doing.
SEED_NONE = """
# No `seed:` block, so a run writes a FRESH implementation from your
# requirements. The file you scaffolded from was read only for its signatures.
# This is the task to keep if you scaffolded from code you intend to replace.
"""

SEED_EXISTING = """
# The code you already have is the thing under test. The suite is still written
# from your acceptance_criteria by an agent that never reads this file, so a
# failure here is a real finding about code you did not write.
seed:
  implementation: "{source_rel}"
"""


def _signature(fn):
    """A readable signature line for one top level function."""
    args = []
    a = fn.args
    for i, arg in enumerate(a.args):
        text = arg.arg
        if arg.annotation is not None:
            try:
                text += f": {ast.unparse(arg.annotation)}"
            except Exception:
                pass
        args.append(text)
    if a.vararg:
        args.append("*" + a.vararg.arg)
    for arg in a.kwonlyargs:
        args.append(arg.arg)
    if a.kwarg:
        args.append("**" + a.kwarg.arg)
    sig = f"{fn.name}({', '.join(args)})"
    if fn.returns is not None:
        try:
            sig += f" -> {ast.unparse(fn.returns)}"
        except Exception:
            pass
    return sig


def read_functions(source):
    """
    Top level public functions, in file order.

    Nested and underscore-prefixed functions are skipped: the interface block
    describes what tests may call, and a helper is not that.
    """
    tree = ast.parse(source)
    out = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                out.append(node)
    return out


def guess_entrypoint(functions):
    """
    Which function runs the whole thing end to end.

    Prefers an explicit run_* name, then main, then whichever function takes
    the most arguments, on the reasoning that an end to end entry usually
    takes both an input and an output. It is a guess and the generated file
    says so.
    """
    names = [f.name for f in functions]
    for f in functions:
        if f.name.startswith("run_"):
            return f
    for f in functions:
        if f.name in ("main", "process", "execute"):
            return f
    return max(functions, key=lambda f: len(f.args.args)) if functions else None


def module_path(source_path, project_root):
    """Dotted module path for a file inside the project."""
    rel = os.path.relpath(os.path.abspath(source_path), os.path.abspath(project_root))
    rel = rel.replace(os.sep, "/")
    if rel.endswith(".py"):
        rel = rel[:-3]
    return rel.replace("/", ".")


def build_task(source_path, project_root, task_id=None, inputs=None, seed=None):
    """The task YAML text for one Python file, or a reason it cannot be built."""
    # utf-8-sig, not utf-8: Python runs a file that starts with a byte-order
    # mark, and Windows tools write one routinely (PowerShell 5.1's
    # `Set-Content -Encoding utf8`, older Notepad). Read as plain utf-8, the mark
    # survives as U+FEFF and ast.parse rejects a file Python itself accepts.
    with open(source_path, "r", encoding="utf-8-sig", errors="replace") as handle:
        source = handle.read()
    try:
        functions = read_functions(source)
    except SyntaxError as e:
        return None, f"{source_path} does not parse: {e}"
    if not functions:
        return None, (f"{source_path} has no public top level functions, so there is "
                      f"no interface to describe. Tests need something to call.")

    stem = os.path.splitext(os.path.basename(source_path))[0]
    task_id = task_id or "".join(c if c.isalnum() else "_" for c in stem).upper()
    entry = guess_entrypoint(functions)
    inputs = inputs or [f"inputs_private/data/{task_id}/input_01.csv"]

    fn_lines = "\n".join(
        f'    - "{_signature(f)}  # TODO: what it does"' for f in functions)
    in_lines = "\n".join(f'  - "{p}"' for p in inputs)

    source_rel = os.path.relpath(source_path, project_root).replace(os.sep, "/")
    seed_block = {
        None: SEED_NONE,
        "none": SEED_NONE,
        "existing": SEED_EXISTING.format(source_rel=source_rel),
    }[seed]

    return TASK_TEMPLATE.format(
        seed_block=seed_block,
        task_id=task_id,
        task_name=f"{task_id}: TODO one line summary",
        description="TODO: one paragraph on what this module is for",
        inputs=in_lines,
        module=module_path(source_path, project_root),
        functions=fn_lines,
        entrypoint=f"{_signature(entry)}  # guessed, check this",
        source_rel=os.path.relpath(source_path, project_root).replace(os.sep, "/"),
    ), None


STARTER_TASK = '''# A starter task. Replace it, or copy it and edit.
#
# The two sections that matter are `requirements` and `acceptance_criteria`,
# and the difference between them is the whole design: the coding agent reads
# requirements and never reads acceptance_criteria, while test generation
# reads both. A criterion the agent could see is a criterion it can write code
# to satisfy without ever being tested on it.
task_id: "MY_FIRST_TASK"

task_name: "My first task"

description: "Replace this with what the module is for."

inputs:
  - "inputs_private/data/MY_FIRST_TASK/input_01.csv"

outputs:
  - "outputs/data/MY_FIRST_TASK/output.json"

interface:
  module: "outputs.agent_src.code.MY_FIRST_TASK.pipeline"
  integration_functions:
    - "extract(input_path) -> list[dict]  # reads one input file"
    - "transform(rows) -> dict  # validates, returns {\\"accepted\\": [...], \\"rejected\\": [...]}"
    - "load(data, output_path) -> None  # writes the result as JSON"
  system_entrypoint: "run_pipeline(input_paths, output_path) -> None"

requirements:
  - "Read the input CSV and validate each row"
  - "Write accepted and rejected rows to the output as JSON, each rejected row keeping a reason"

# Never shown to the coding agent. Write boundary values explicitly.
acceptance_criteria:
  - "A quantity of 0 is rejected and a quantity of 1 is accepted"
  - "A row with an empty identifier is rejected with a reason naming the field"
'''


def init_project(root):
    """Create the directories and starter files a run needs. Never overwrites."""
    made, skipped = [], []
    dirs = [
        os.path.join(root, "inputs_private", "config", "tasks"),
        os.path.join(root, "inputs_private", "data", "MY_FIRST_TASK"),
        os.path.join(root, "outputs"),
    ]
    for d in dirs:
        if os.path.isdir(d):
            skipped.append(d)
        else:
            os.makedirs(d, exist_ok=True)
            made.append(d)

    files = {
        os.path.join(root, "inputs_private", "config", "tasks", "MY_FIRST_TASK.yaml"):
            STARTER_TASK,
        os.path.join(root, "inputs_private", "data", "MY_FIRST_TASK", "input_01.csv"):
            "identifier,quantity\nWIDGET-1,5\n,10\nWIDGET-2,0\n",
        os.path.join(root, "inputs_private", "config", "settings.yaml"):
            textwrap.dedent("""\
                # Your overrides. Anything absent falls back to the bundled defaults,
                # one top level section at a time, so you only state what you change.
                #
                # test_generation:
                #   criteria_per_batch: 4   # one generation call per 4 criteria
                #
                # agents:
                #   default:
                #     provider: gemini
                #     model: gemini-3.5-flash-lite
                """),
    }
    for path, body in files.items():
        if os.path.exists(path):
            skipped.append(path)
            continue
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(body)
        made.append(path)
    return made, skipped
