"""
Start a project, and turn existing code into a task the tool can verify.

Two commands, both aimed at the same gap. Until now a fresh `pip install
qikly` produced a CLI that needed an `inputs_private/config/tasks/` directory
it had no way to create, and the use case the tool exists for, verifying code
somebody else wrote, required hand-writing a fifty line YAML whose
`interface:` block restates function signatures already present in the file
being pointed at.

`init` creates the directory layout and a commented starter task.

`scaffold` reads a Python file and writes the task for it: module path,
integration functions with their real signatures, and a system entrypoint
guess. It deliberately does NOT write `acceptance_criteria`. Those are the one
part that cannot be derived from the code, because criteria derived from an
implementation can only ever describe what that implementation already does,
and a bar that agrees with the code by construction is the exact failure this
whole tool exists to prevent.
"""
import ast
import os
import textwrap

TASK_TEMPLATE = '''# Generated by `qikly scaffold`. Two sections need you.
task_id: "{task_id}"

task_name: "{task_name}"

description: "{description}"

inputs:
{inputs}

outputs:
  - "outputs/data/{task_id}/output.json"

# Read out of {source_rel}. Check the entrypoint: it was guessed from the
# function names, and the guess is only as good as the naming. Each `e.g.`
# below shows the shape of a useful answer, not a claim about your function.
# Replace it with what yours actually does.
interface:
  module: "{module}"
  integration_functions:
{functions}
  system_entrypoint: "{entrypoint}"

# TODO. The decisions: what the code must do, in the words a person would use,
# including any choice that could have gone another way, such as a threshold, a
# unit or an exemption. The coding agent sees this section.
requirements:
  - "TODO: describe what this module must do, e.g. a reading whose temperature
    is missing or non-numeric is dropped, and its station still appears in the
    output with whatever readings remain"

# TODO. The consequences: what must be true if those decisions are implemented
# correctly, each naming its boundary value. The coding agent NEVER sees this
# section; test generation sees it in full, and that asymmetry is the whole
# point. Deriving these from the code would defeat it, so they are left for you.
#
# Write "rejects 0 and accepts 1" rather than "must be positive": the first
# forces a test at the boundary, the second invites a test at 5.
#
# And keep them out of the comments. Only this section is withheld: every other
# line of this file, comments included, goes to the coding agent as written. A
# note above saying which way a boundary falls is that boundary, handed over by
# a route nobody thinks to check. `qikly --validate` looks for it.
acceptance_criteria:
  - "TODO: one checkable statement, with its boundary value, e.g. a humidity of
    100 is accepted and 101 is rejected"
{seed_block}'''


# A scaffold writes one of two task files, because one command cannot know which
# of two jobs you meant. The default, SEED_EXISTING, tests the code you already
# have; `--fresh` picks SEED_NONE and a new implementation instead.
# The task that tests existing code is <NAME>_VERIFY, so it never collides with
# the <NAME> a `--fresh` scaffold of the same file writes.
VERIFY_SUFFIX = "_VERIFY"

SEED_NONE = """
# No `seed:` block, so a run writes a FRESH implementation from your
# requirements. The file you scaffolded from was read only for its signatures.
# This is the task to keep if you scaffolded from code you intend to replace.
"""

SEED_EXISTING = """
# The code you already have is the thing under test. The suite is still written
# from your acceptance_criteria by an agent that never reads this file, so a
# failure here is a finding about the code rather than a test written to fit it.
#
# What this cannot tell you is what the author of that code saw. Withholding is
# a property of a run qikly performed, not of a file you supply: if the code
# was written with these criteria open, the suite is still independent of the
# code, but the author was not.
#
# What a run can do is ask git. If this task file was last changed before the
# implementation's first commit, the criteria were not written against code
# that was already in the repository, and the run says so as it starts and in
# its report. Read that narrowly, because it is a narrow claim: code can have
# existed uncommitted while the criteria were being written, and criteria
# committed first say nothing about whether the code's author read them, which
# no ordering of commits can show. So the run prints those bounds alongside the
# verdict, and reports whether the two sides were committed by the same person.
seed:
  implementation: "{source_rel}"
"""


def _signature(fn):
    """A readable signature line for one top level function."""
    args = []
    a = fn.args
    for i, arg in enumerate(a.args):
        text = arg.arg
        if arg.annotation is not None:
            try:
                text += f": {ast.unparse(arg.annotation)}"
            except Exception:
                pass
        args.append(text)
    if a.vararg:
        args.append("*" + a.vararg.arg)
    for arg in a.kwonlyargs:
        args.append(arg.arg)
    if a.kwarg:
        args.append("**" + a.kwarg.arg)
    sig = f"{fn.name}({', '.join(args)})"
    if fn.returns is not None:
        try:
            sig += f" -> {ast.unparse(fn.returns)}"
        except Exception:
            pass
    return sig


def read_functions(source):
    """
    Top level public functions, in file order.

    Nested and underscore-prefixed functions are skipped: the interface block
    describes what tests may call, and a helper is not that.
    """
    tree = ast.parse(source)
    out = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                out.append(node)
    return out


def guess_entrypoint(functions):
    """
    Which function runs the whole thing end to end.

    Prefers an explicit run_* name, then main, then whichever function takes
    the most arguments, on the reasoning that an end to end entry usually
    takes both an input and an output. It is a guess and the generated file
    says so.
    """
    names = [f.name for f in functions]
    for f in functions:
        if f.name.startswith("run_"):
            return f
    for f in functions:
        if f.name in ("main", "process", "execute"):
            return f
    return max(functions, key=lambda f: len(f.args.args)) if functions else None


def _relative_to(path, start):
    """
    `path` relative to `start`, or None when no relative path exists.

    On Windows there is no relative path between two drives, and
    os.path.relpath raises instead of answering. A module on D: scaffolded for a
    project on C: failed with "path is on mount 'D:', start on mount 'C:'",
    which is also how GitHub's Windows runners are laid out: the checkout on D:,
    temporary directories on C:.
    """
    try:
        return os.path.relpath(os.path.abspath(path), os.path.abspath(start))
    except ValueError:
        return None


def module_path(source_path, task_id):
    """
    The dotted path a run's tests import this module by.

    A run installs the implementation, seeded or generated, into
    outputs/agent_src/code/<task_id>/ under the file's own name, and runs pytest
    from the project root. So the module is outputs.agent_src.code.<task_id>.
    <file name>, wherever the original lives. It used to be the path relative
    to the project root, which made every test import the original file rather
    than the copy the coding agent patches, so no fix could ever reach a test.
    """
    stem = os.path.splitext(os.path.basename(source_path))[0]
    return "outputs.agent_src.code.%s.%s" % (task_id, stem)


def _source_rel(source_path, project_root):
    """The seed path as a task records it: relative when it can be, else absolute."""
    rel = _relative_to(source_path, project_root)
    return (rel if rel is not None else os.path.abspath(source_path)).replace(os.sep, "/")


def build_task(source_path, project_root, task_id=None, inputs=None, seed=None):
    """The task YAML text for one Python file, or a reason it cannot be built."""
    # utf-8-sig, not utf-8: Python runs a file that starts with a byte-order
    # mark, and Windows tools write one routinely (PowerShell 5.1's
    # `Set-Content -Encoding utf8`, older Notepad). Read as plain utf-8, the mark
    # survives as U+FEFF and ast.parse rejects a file Python itself accepts.
    with open(source_path, "r", encoding="utf-8-sig", errors="replace") as handle:
        source = handle.read()
    try:
        functions = read_functions(source)
    except SyntaxError as e:
        return None, f"{source_path} does not parse: {e}"
    if not functions:
        return None, (f"{source_path} has no public top level functions, so there is "
                      f"no interface to describe. Tests need something to call.")

    stem = os.path.splitext(os.path.basename(source_path))[0]
    base = task_id or "".join(c if c.isalnum() else "_" for c in stem).upper()
    # Named here, not by each caller, so `--scaffold` and the MCP tool cannot
    # disagree about what the task that tests existing code is called. Both
    # jobs share one data folder, since they read the same inputs.
    task_id = base + (VERIFY_SUFFIX if seed == "existing" else "")
    entry = guess_entrypoint(functions)
    inputs = inputs or [f"inputs_private/data/{base}/input_01.csv"]

    fn_lines = "\n".join(
        f'    - "{_signature(f)}  # TODO: what it does, e.g. reads one CSV and '
        f'returns its rows"' for f in functions)
    in_lines = "\n".join(f'  - "{p}"' for p in inputs)

    source_rel = _source_rel(source_path, project_root)
    seed_block = {
        None: SEED_NONE,
        "none": SEED_NONE,
        "existing": SEED_EXISTING.format(source_rel=source_rel),
    }[seed]

    return TASK_TEMPLATE.format(
        seed_block=seed_block,
        task_id=task_id,
        task_name=f"{task_id}: TODO one line summary, e.g. per-station daily temperature and humidity metrics",
        description="TODO: one paragraph on what this module is for, e.g. reads raw sensor CSVs, drops unusable readings, and writes one record per station per day",
        inputs=in_lines,
        module=module_path(source_path, task_id),
        functions=fn_lines,
        entrypoint=f"{_signature(entry)}  # guessed, check this",
        source_rel=_source_rel(source_path, project_root),
    ), None


STARTER_TASK = '''# A starter task. Replace it, or copy it and edit.
#
# The two sections that matter are `requirements` and `acceptance_criteria`,
# and the difference between them is the whole design: the coding agent reads
# requirements and never reads acceptance_criteria, while test generation
# reads both. A criterion the agent could see is a criterion it can write code
# to satisfy without ever being tested on it.
#
# Decisions go in requirements: anything that could have gone another way, such
# as a threshold, a unit or an exemption, because the agent cannot guess it.
# Consequences go in acceptance_criteria: what must be true if those decisions
# are implemented correctly. If two careful developers could disagree about a
# line, it is a decision.
task_id: "MY_FIRST_TASK"

task_name: "My first task"

description: "Replace this with what the module is for."

inputs:
  - "inputs_private/data/MY_FIRST_TASK/input_01.csv"

outputs:
  - "outputs/data/MY_FIRST_TASK/output.json"

interface:
  module: "outputs.agent_src.code.MY_FIRST_TASK.pipeline"
  integration_functions:
    - "extract(input_path) -> list[dict]  # reads one input file"
    - "transform(rows) -> dict  # validates, returns {\\"accepted\\": [...], \\"rejected\\": [...]}"
    - "load(data, output_path) -> None  # writes the result as JSON"
  system_entrypoint: "run_pipeline(input_paths, output_path) -> None"

requirements:
  - "Read the input CSV and validate each row"
  - "A row is valid only if its identifier is non-empty and its quantity is a positive whole number"
  - "Write the result as JSON, keeping every valid row and every invalid row, and give each invalid row the reason it failed"

# Never shown to the coding agent. The consequences, with boundary values written out.
acceptance_criteria:
  - "A quantity of 0 is rejected and a quantity of 1 is accepted"
  - "A row with an empty identifier is rejected with a reason naming the field"
'''


def init_project(root, starter=True):
    """
    Create the directories and starter files a run needs. Never overwrites.

    `starter=False` leaves out MY_FIRST_TASK, for `--example`, which brings a
    finished task of its own. Handing someone both meant two tasks in their
    project on their first command, one of which nothing in the documentation
    mentioned, and a later bare `qikly` would have run the pair.
    """
    made, skipped = [], []
    dirs = [
        os.path.join(root, "inputs_private", "config", "tasks"),
        os.path.join(root, "outputs"),
    ]
    if starter:
        dirs.insert(1, os.path.join(root, "inputs_private", "data", "MY_FIRST_TASK"))
    for d in dirs:
        if os.path.isdir(d):
            skipped.append(d)
        else:
            os.makedirs(d, exist_ok=True)
            made.append(d)

    files = {
        os.path.join(root, "inputs_private", "config", "settings.yaml"):
            textwrap.dedent("""\
                # Your overrides. Anything absent falls back to the bundled defaults,
                # one top level section at a time, so you only state what you change.
                #
                # test_generation:
                #   criteria_per_batch: 4   # one generation call per 4 criteria
                #
                # agents:
                #   default:
                #     provider: gemini
                #     model: gemini-3.5-flash-lite
                """),
    }
    if starter:
        files[os.path.join(root, "inputs_private", "config", "tasks",
                           "MY_FIRST_TASK.yaml")] = STARTER_TASK
        files[os.path.join(root, "inputs_private", "data", "MY_FIRST_TASK",
                           "input_01.csv")] = (
            "identifier,quantity\nWIDGET-1,5\n,10\nWIDGET-2,0\n")

    for path, body in files.items():
        if os.path.exists(path):
            skipped.append(path)
            continue
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(body)
        made.append(path)
    return made, skipped


# The worked example ships in the wheel under inputs_public/examples/, laid out
# the way a real project is. Nothing copies it out on its own: it is not a
# bundled task, so ensure_task_data never sees it and the task loader never
# scans it. This map is the one route from the package into a project, and the
# destinations are exactly the paths the two task files already name, so the
# example runs the moment it lands.
#
# my_metrics.py goes to the project root rather than under inputs_private/
# because MY_METRICS_VERIFY.yaml records its seed as `implementation:
# "my_metrics.py"`, relative to the root. Put it anywhere else and the seeded
# task cannot find the code it is meant to test.
EXAMPLE_FILES = {
    ("config", "tasks", "MY_METRICS.yaml"):
        ("inputs_private", "config", "tasks", "MY_METRICS.yaml"),
    ("config", "tasks", "MY_METRICS_VERIFY.yaml"):
        ("inputs_private", "config", "tasks", "MY_METRICS_VERIFY.yaml"),
    ("data", "MY_METRICS", "input_01.csv"):
        ("inputs_private", "data", "MY_METRICS", "input_01.csv"),
    ("data", "MY_METRICS", "input_02.csv"):
        ("inputs_private", "data", "MY_METRICS", "input_02.csv"),
    ("reference", "MY_METRICS", "my_metrics.py"):
        ("my_metrics.py",),
}


def example_source_dir():
    """Where the shipped example lives inside the installed package."""
    from qikly.paths import PUBLIC_INPUTS_DIR

    return os.path.join(PUBLIC_INPUTS_DIR, "examples")


def install_example(root):
    """
    Copy the worked example into a project, at the paths its task files name.

    Same contract as init_project: never overwrites, and reports what it wrote
    and what it left alone. A reader who has already edited my_metrics.py keeps
    their version, and the run that follows tests theirs rather than ours.

    Returns (made, skipped, missing). `missing` is non-empty only if the wheel
    was built without the examples, which is reported rather than raised so a
    partial install is never left behind silently.
    """
    import shutil

    source_dir = example_source_dir()
    made, skipped, missing = [], [], []
    for source_parts, dest_parts in sorted(EXAMPLE_FILES.items()):
        source = os.path.join(source_dir, *source_parts)
        dest = os.path.join(root, *dest_parts)
        if not os.path.isfile(source):
            missing.append("/".join(source_parts))
            continue
        if os.path.exists(dest):
            skipped.append(dest)
            continue
        os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
        shutil.copyfile(source, dest)
        made.append(dest)
    return made, skipped, missing
